/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aimSystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author stefa
 *  PLEASE DON'T REMOVE CREDITS SECTION
 *                               -GRP 4
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public SignUp() {
        initComponents();
        Connect();
    }
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    
    public void Connect(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con =DriverManager.getConnection("jdbc:mysql://localhost/online_quizz","root","");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
        }catch (SQLException ex) {
            Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);    
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        FirstName = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        LastName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        sNumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        sProg = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        sPwd = new javax.swing.JPasswordField();
        sUsername = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        savetostud = new javax.swing.JCheckBox();
        savetofaculty = new javax.swing.JCheckBox();
        subject = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        male = new javax.swing.JCheckBox();
        female = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        sSec = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(25, 49, 83));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/pillogo.png"))); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/up (3).png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Gotham", 1, 9)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("BY ESTEPANO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(jLabel14))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jLabel8)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(29, 29, 29))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Gotham Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("PLEASE SIGN UP");

        jLabel2.setFont(new java.awt.Font("Manrope Light", 0, 12)); // NOI18N
        jLabel2.setText("Student No. (If student)");

        jLabel3.setFont(new java.awt.Font("Manrope Light", 0, 12)); // NOI18N
        jLabel3.setText("Password*");

        FirstName.setBackground(new java.awt.Color(239, 239, 239));
        FirstName.setBorder(null);

        jButton2.setBackground(new java.awt.Color(25, 49, 83));
        jButton2.setFont(new java.awt.Font("Manrope Light", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("SIGN UP");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        LastName.setBackground(new java.awt.Color(239, 239, 239));
        LastName.setBorder(null);

        jLabel12.setFont(new java.awt.Font("Manrope Light", 0, 12)); // NOI18N
        jLabel12.setText("First Name*");

        jLabel13.setFont(new java.awt.Font("Manrope Light", 0, 12)); // NOI18N
        jLabel13.setText("Last Name*");

        sNumber.setBackground(new java.awt.Color(239, 239, 239));
        sNumber.setBorder(null);

        jLabel4.setFont(new java.awt.Font("Manrope Light", 0, 12)); // NOI18N
        jLabel4.setText("Username*");

        sProg.setBackground(new java.awt.Color(239, 239, 239));
        sProg.setBorder(null);

        jLabel25.setFont(new java.awt.Font("Manrope Light", 0, 12)); // NOI18N
        jLabel25.setText("Program (If student)");

        sPwd.setBackground(new java.awt.Color(239, 239, 239));
        sPwd.setBorder(null);
        sPwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sPwdActionPerformed(evt);
            }
        });

        sUsername.setBackground(new java.awt.Color(239, 239, 239));
        sUsername.setBorder(null);

        jLabel5.setFont(new java.awt.Font("Manrope", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Sign Up now for exclusive academic features ");

        jLabel16.setFont(new java.awt.Font("Manrope", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("and experience");

        savetostud.setBackground(new java.awt.Color(255, 255, 255));
        savetostud.setFont(new java.awt.Font("Manrope Light", 0, 12)); // NOI18N
        savetostud.setText("Student");
        savetostud.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        savetostud.setOpaque(true);
        savetostud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savetostudActionPerformed(evt);
            }
        });

        savetofaculty.setBackground(new java.awt.Color(255, 255, 255));
        savetofaculty.setFont(new java.awt.Font("Manrope Light", 0, 12)); // NOI18N
        savetofaculty.setText("Faculty");
        savetofaculty.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        savetofaculty.setOpaque(true);
        savetofaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savetofacultyActionPerformed(evt);
            }
        });

        subject.setBackground(new java.awt.Color(239, 239, 239));
        subject.setBorder(null);

        jLabel6.setFont(new java.awt.Font("Manrope Light", 0, 12)); // NOI18N
        jLabel6.setText("Subject Taught (if instructor)");

        male.setBackground(new java.awt.Color(255, 255, 255));
        male.setFont(new java.awt.Font("Manrope Light", 0, 12)); // NOI18N
        male.setText("Male");
        male.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        male.setOpaque(true);
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });

        female.setBackground(new java.awt.Color(255, 255, 255));
        female.setFont(new java.awt.Font("Manrope Light", 0, 12)); // NOI18N
        female.setText("Female");
        female.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        female.setOpaque(true);
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Manrope Light", 0, 12)); // NOI18N
        jLabel17.setText("Sex*");

        jPanel3.setBackground(new java.awt.Color(253, 225, 8));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(253, 225, 8));
        jLabel7.setFont(new java.awt.Font("Manrope ExtraBold", 1, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText(" <");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(22, 22, 22))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel26.setFont(new java.awt.Font("Manrope Light", 0, 12)); // NOI18N
        jLabel26.setText("Section(If student)");

        sSec.setBackground(new java.awt.Color(239, 239, 239));
        sSec.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(102, 102, 102)
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(sUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel26))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(subject, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sSec, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(104, 104, 104)
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(savetostud, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(savetofaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(sPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(131, 131, 131)
                            .addComponent(jLabel1))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(131, 131, 131)
                            .addComponent(jLabel5))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(131, 131, 131)
                            .addComponent(jLabel16))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(166, 166, 166)
                            .addComponent(jLabel12)
                            .addGap(18, 18, 18)
                            .addComponent(FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(96, 96, 96)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel17)
                                .addComponent(jLabel13)
                                .addComponent(jLabel2)
                                .addComponent(jLabel25))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(sNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(male, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(female, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(sProg, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(jLabel5)
                .addGap(6, 6, 6)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel12))
                    .addComponent(FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(female)
                    .addComponent(male)
                    .addComponent(jLabel17))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(sNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sProg, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sSec, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(sUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(subject, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savetofaculty)
                    .addComponent(savetostud))
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
    String firstName = FirstName.getText();
    String lastName = LastName.getText();
    String sex = "";

    if (male.isSelected()) {
        sex = "male";
    } else if (female.isSelected()) {
        sex = "female";
    }

    String studNum = sNumber.getText();
    String studProg = sProg.getText();
    String studSec = sSec.getText();
    String subT = subject.getText();
    String username = sUsername.getText();
    String pwd = sPwd.getText();

    boolean saveToRegStudent = savetostud.isSelected();
    boolean saveToFacultyList = savetofaculty.isSelected();

    int kRegStudent = 0;
    int kFacultyList = 0;

    // Check if the username already exists in reg_student table
    pst = con.prepareStatement("SELECT COUNT(*) FROM reg_student WHERE username = ?");
    pst.setString(1, username);
    rs = pst.executeQuery();
    rs.next();
    int regStudentCount = rs.getInt(1);

    // Check if the username already exists in faculty_list table
    pst = con.prepareStatement("SELECT COUNT(*) FROM faculty_list WHERE username = ?");
    pst.setString(1, username);
    rs = pst.executeQuery();
    rs.next();
    int facultyListCount = rs.getInt(1);

    if (regStudentCount > 0 || facultyListCount > 0) {
        // Username already exists
        JOptionPane.showMessageDialog(this, "Username already exists :(");
    } else {
        if (saveToRegStudent) {
            // INSERT into reg_student table
            pst = con.prepareStatement("INSERT INTO reg_student(firstname, lastname, sex, sNumber, sProg, sSec, username, password) VALUES(?,?,?,?,?,?,?,?)");
            pst.setString(1, firstName);
            pst.setString(2, lastName);
            pst.setString(3, sex);
            pst.setString(4, studNum);
            pst.setString(5, studProg);
            pst.setString(6, studSec);
            pst.setString(7, username);
            pst.setString(8, pwd);

            kRegStudent = pst.executeUpdate();

            // Retrieve distinct quiz titles from quiz_list table
            String query = "SELECT DISTINCT `program`, `yrSection`, `subject`, `title`, `timeLimit`, `pointsperitem`, `faculty`, `completion_status` FROM quiz_list";
            pst = con.prepareStatement(query);
            rs = pst.executeQuery();

            // Prepare and execute the INSERT statement with username into quiz_list table
            pst = con.prepareStatement("INSERT INTO quiz_list (`program`,`yrSection`, `subject`, `title`, `timeLimit`, `pointsperitem`, `faculty`, `username`, `completion_status`) " +
                    "VALUES (?,?,?,?,?,?,?,?,?)");

            while (rs.next()) {
                // Retrieve data from the result set
                String pRogram = rs.getString("program");
                String yrSec = rs.getString("yrSection");
                String sUb = rs.getString("subject");
                String title = rs.getString("title");
                String time_limit = rs.getString("timeLimit");
                int pointsPerItem = rs.getInt("pointsperitem");
                String faculty = rs.getString("faculty");
                

                // Set values in the prepared statement
                pst.setString(1, pRogram);
                pst.setString(2, yrSec);
                pst.setString(3, sUb);
                pst.setString(4, title);
                pst.setString(5, time_limit);
                pst.setInt(6, pointsPerItem);
                pst.setString(7, faculty);
                pst.setString(8, username);
                pst.setString(9, "Not Yet Taken");

                // Execute the INSERT statement
                pst.executeUpdate();
            }
            
            DashBoardStud db = new DashBoardStud(username);
            db.FetchStud(username);
            db.show();
            dispose();
        }

        if (saveToFacultyList) {
            // INSERT into faculty_list table
            pst = con.prepareStatement("INSERT INTO faculty_list(firstname, lastname, sex, subject, username, password) VALUES(?,?,?,?,?,?)");
            pst.setString(1, firstName);
            pst.setString(2, lastName);
            pst.setString(3, sex);
            pst.setString(4, subT);
            pst.setString(5, username);
            pst.setString(6, pwd);

            kFacultyList = pst.executeUpdate();
            DashBoard dash = new DashBoard(username);
            dash.Fetch(username);
            dash.show();
            dispose();
        }

        if (kRegStudent == 1 || kFacultyList == 1) {
            FirstName.setText("");
            LastName.setText("");
            sNumber.setText("");
            sProg.setText("");
            subject.setText("");
            sUsername.setText("");
            sPwd.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Input");
        }
    }
} catch (SQLException ex) {
    Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
}

    }//GEN-LAST:event_jButton2ActionPerformed

    private void savetofacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savetofacultyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savetofacultyActionPerformed

    private void savetostudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savetostudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savetostudActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleActionPerformed

    private void sPwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sPwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sPwdActionPerformed

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        HomePage hp = new HomePage();
        hp.setVisible(true);
        dispose();
    }//GEN-LAST:event_jPanel3MouseClicked

    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FirstName;
    private javax.swing.JTextField LastName;
    private javax.swing.JCheckBox female;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JCheckBox male;
    private javax.swing.JTextField sNumber;
    private javax.swing.JTextField sProg;
    private javax.swing.JPasswordField sPwd;
    private javax.swing.JTextField sSec;
    private javax.swing.JTextField sUsername;
    private javax.swing.JCheckBox savetofaculty;
    private javax.swing.JCheckBox savetostud;
    private javax.swing.JTextField subject;
    // End of variables declaration//GEN-END:variables
}
