/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package aimSystem;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
/**
 *
 * @author stefa
 */
public class StatusPanel extends javax.swing.JPanel {
    private String userName;
    
    /**
     * Creates new form StatusPanel
     */
    public StatusPanel() {
        initComponents();
    }
    
    public void initEvent(TableActionEvent event, int row){
        takequiz.addActionListener(new ActionListener(){
        @Override
        public void actionPerformed(ActionEvent ae){
            event.onTakeQuiz(row);
            
        }
    }); completed.setEnabled(false);
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        takequiz = new aimSystem.StatusButton();
        completed = new aimSystem.StatusButton();

        setBackground(new java.awt.Color(255, 255, 255));

        takequiz.setForeground(new java.awt.Color(255, 204, 102));
        takequiz.setText("TAKE QUIZ");
        takequiz.setFont(new java.awt.Font("Manrope ExtraBold", 0, 14)); // NOI18N
        takequiz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                takequizMouseClicked(evt);
            }
        });
        takequiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takequizActionPerformed(evt);
            }
        });

        completed.setText("COMPLETED");
        completed.setFont(new java.awt.Font("Manrope ExtraBold", 0, 14)); // NOI18N
        completed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                completedMouseClicked(evt);
            }
        });
        completed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(completed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(takequiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(takequiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(completed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void takequizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_takequizActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_takequizActionPerformed

    private void takequizMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_takequizMouseClicked
        
    }//GEN-LAST:event_takequizMouseClicked

    private void completedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_completedActionPerformed

    private void completedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_completedMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_completedMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public aimSystem.StatusButton completed;
    public aimSystem.StatusButton takequiz;
    // End of variables declaration//GEN-END:variables
}
