/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package aimSystem;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
/**
 *
 * @author stefa
 */
public class StatusPanel2 extends javax.swing.JPanel {
    private String userName;
    
    /**
     * Creates new form StatusPanel
     */
    public StatusPanel2() {
        initComponents();
    }
    
    public void initEvent(TableActionEvent2 event, int row){
        manages.addActionListener(new ActionListener(){
        @Override
        public void actionPerformed(ActionEvent ae){
            event.onManages(row);
            
        }
    }); 
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manages = new aimSystem.StatusButton();

        setBackground(new java.awt.Color(255, 255, 255));

        manages.setBackground(new java.awt.Color(0, 102, 204));
        manages.setForeground(new java.awt.Color(0, 102, 204));
        manages.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8-manage-23.png"))); // NOI18N
        manages.setText("Manage");
        manages.setFont(new java.awt.Font("Manrope Medium", 0, 14)); // NOI18N
        manages.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                managesMouseClicked(evt);
            }
        });
        manages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(manages, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(manages, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void managesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_managesActionPerformed

    private void managesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managesMouseClicked
        
    }//GEN-LAST:event_managesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public aimSystem.StatusButton manages;
    // End of variables declaration//GEN-END:variables
}
